"""Dewey Decimal Classification lookup tables."""

# Tens-level labels (divisions, ~100 entries)
DEWEY_TENS_LABELS: dict[str, str] = {
    "000": "Computer Science & Information",
    "010": "Bibliographies",
    "020": "Library & Information Science",
    "030": "Encyclopedias & General Reference",
    "040": "Unassigned",
    "050": "Magazines, Journals & Serials",
    "060": "Associations, Organizations & Museums",
    "070": "News Media, Journalism & Publishing",
    "080": "General Collections & Anthologies",
    "090": "Manuscripts & Rare Books",
    "100": "Philosophy",
    "110": "Metaphysics",
    "120": "Epistemology & Causation",
    "130": "Parapsychology & Occultism",
    "140": "Philosophical Schools of Thought",
    "150": "Psychology",
    "160": "Logic",
    "170": "Ethics",
    "180": "Ancient, Medieval & Eastern Philosophy",
    "190": "Modern Western Philosophy",
    "200": "Religion",
    "210": "Philosophy of Religion",
    "220": "The Bible",
    "230": "Christianity & Christian Theology",
    "240": "Christian Practice & Observance",
    "250": "Christian Pastoral Practice",
    "260": "Christian Organization & Social Work",
    "270": "History of Christianity",
    "280": "Christian Denominations",
    "290": "Other Religions",
    "300": "Social Sciences",
    "310": "Statistics",
    "320": "Political Science",
    "330": "Economics",
    "340": "Law",
    "350": "Public Administration & Military",
    "360": "Social Problems & Services",
    "370": "Education",
    "380": "Commerce, Communications & Transportation",
    "390": "Customs, Etiquette & Folklore",
    "400": "Language",
    "410": "Linguistics",
    "420": "English & Old English",
    "430": "German & Related Languages",
    "440": "French & Related Languages",
    "450": "Italian, Romanian & Related",
    "460": "Spanish & Portuguese",
    "470": "Latin",
    "480": "Classical Greek",
    "490": "Other Languages",
    "500": "Science",
    "510": "Mathematics",
    "520": "Astronomy",
    "530": "Physics",
    "540": "Chemistry",
    "550": "Earth Sciences & Geology",
    "560": "Fossils & Prehistoric Life",
    "570": "Biology & Life Sciences",
    "580": "Plants (Botany)",
    "590": "Animals (Zoology)",
    "600": "Technology",
    "610": "Medicine & Health",
    "620": "Engineering",
    "630": "Agriculture",
    "640": "Home & Family Management",
    "650": "Management & Public Relations",
    "660": "Chemical Engineering",
    "670": "Manufacturing",
    "680": "Specific Manufactured Products",
    "690": "Building & Construction",
    "700": "Arts & Recreation",
    "710": "Landscape & Area Planning",
    "720": "Architecture",
    "730": "Sculpture, Ceramics & Metalwork",
    "740": "Drawing & Decorative Arts",
    "750": "Painting",
    "760": "Printmaking & Graphic Arts",
    "770": "Photography & Computer Art",
    "780": "Music",
    "790": "Sports, Games & Entertainment",
    "800": "Literature",
    "810": "American Literature in English",
    "820": "English & Old English Literature",
    "830": "German Literature",
    "840": "French Literature",
    "850": "Italian Literature",
    "860": "Spanish & Portuguese Literature",
    "870": "Latin Literature",
    "880": "Classical Greek Literature",
    "890": "Other Literatures",
    "900": "History & Geography",
    "910": "Geography & Travel",
    "920": "Biography & Genealogy",
    "930": "Ancient World History",
    "940": "European History",
    "950": "Asian History",
    "960": "African History",
    "970": "North American History",
    "980": "South American History",
    "990": "History of Other Areas",
}

# Hundreds-level labels (sections, subset of most common)
DEWEY_HUNDREDS_LABELS: dict[str, str] = {
    "001": "Knowledge",
    "004": "Computer Science",
    "005": "Computer Programming",
    "006": "Special Computer Methods",
    "011": "Bibliographies & Catalogs",
    "016": "Bibliographies of Specific Subjects",
    "020": "Library & Information Science",
    "025": "Library Operations",
    "027": "General Libraries",
    "030": "Encyclopedias",
    "070": "News Media & Journalism",
    "100": "Philosophy",
    "150": "Psychology",
    "152": "Perception & Emotions",
    "153": "Mental Processes & Intelligence",
    "155": "Differential Psychology",
    "158": "Applied Psychology",
    "170": "Ethics",
    "200": "Religion",
    "220": "The Bible",
    "230": "Christian Theology",
    "290": "Other Religions",
    "291": "Comparative Religion",
    "296": "Judaism",
    "297": "Islam",
    "300": "Social Sciences",
    "301": "Sociology & Anthropology",
    "302": "Social Interaction",
    "305": "Social Groups",
    "306": "Culture & Institutions",
    "320": "Political Science",
    "323": "Civil & Political Rights",
    "327": "International Relations",
    "330": "Economics",
    "331": "Labor Economics",
    "332": "Financial Economics",
    "338": "Production",
    "340": "Law",
    "345": "Criminal Law",
    "347": "Civil Procedure & Courts",
    "355": "Military Science",
    "360": "Social Problems & Services",
    "361": "Social Problems & Social Welfare",
    "362": "Social Welfare & Social Work",
    "363": "Other Social Problems",
    "364": "Criminology",
    "370": "Education",
    "371": "Schools & Teaching",
    "372": "Elementary Education",
    "373": "Secondary Education",
    "380": "Commerce & Communications",
    "384": "Communications & Telecommunication",
    "390": "Customs & Folklore",
    "398": "Folklore",
    "400": "Language",
    "410": "Linguistics",
    "420": "English",
    "428": "Standard English Usage",
    "460": "Spanish",
    "500": "Science",
    "510": "Mathematics",
    "512": "Algebra",
    "516": "Geometry",
    "520": "Astronomy",
    "530": "Physics",
    "540": "Chemistry",
    "550": "Earth Sciences",
    "560": "Paleontology",
    "570": "Biology",
    "571": "Physiology",
    "572": "Biochemistry",
    "573": "Specific Physiological Systems",
    "576": "Genetics",
    "577": "Ecology",
    "580": "Botany",
    "590": "Zoology",
    "591": "Zoology (Specific Topics)",
    "599": "Mammals",
    "600": "Technology",
    "610": "Medicine & Health",
    "611": "Human Anatomy",
    "612": "Human Physiology",
    "613": "Personal Health & Safety",
    "614": "Public Health",
    "615": "Pharmacology & Therapeutics",
    "616": "Diseases",
    "617": "Surgery",
    "618": "Gynecology, Obstetrics & Pediatrics",
    "620": "Engineering",
    "621": "Applied Physics",
    "623": "Military Engineering",
    "624": "Civil Engineering",
    "625": "Railroads & Roads",
    "629": "Automotive & Aeronautical Engineering",
    "630": "Agriculture",
    "635": "Garden Crops (Horticulture)",
    "636": "Animal Husbandry",
    "640": "Home & Family Management",
    "641": "Food & Drink",
    "646": "Sewing & Clothing",
    "649": "Child Rearing",
    "650": "Management & Business",
    "658": "General Management",
    "660": "Chemical Engineering",
    "670": "Manufacturing",
    "690": "Building & Construction",
    "700": "Arts",
    "709": "Art History",
    "720": "Architecture",
    "730": "Sculpture",
    "740": "Drawing & Decorative Arts",
    "741": "Drawing & Illustration",
    "745": "Decorative Arts",
    "746": "Textile Arts & Handicrafts",
    "750": "Painting",
    "770": "Photography",
    "780": "Music",
    "784": "Instruments & Ensembles",
    "790": "Recreation & Performing Arts",
    "791": "Public Performances",
    "792": "Stage Presentations & Theater",
    "793": "Indoor Games & Amusements",
    "796": "Athletic & Outdoor Sports",
    "800": "Literature",
    "808": "Rhetoric & Writing",
    "810": "American Literature",
    "811": "American Poetry",
    "812": "American Drama",
    "813": "American Fiction",
    "814": "American Essays",
    "820": "English Literature",
    "821": "English Poetry",
    "822": "English Drama",
    "823": "English Fiction",
    "839": "Germanic Literatures",
    "860": "Spanish Literature",
    "870": "Latin Literature",
    "880": "Greek Literature",
    "900": "History & Geography",
    "910": "Geography & Travel",
    "914": "Europe (Geography)",
    "917": "North America (Geography)",
    "920": "Biography",
    "930": "Ancient World History",
    "940": "European History",
    "941": "British Isles History",
    "943": "German History",
    "944": "French History",
    "945": "Italian History",
    "950": "Asian History",
    "951": "Chinese History",
    "952": "Japanese History",
    "960": "African History",
    "970": "North American History",
    "971": "Canadian History",
    "972": "Mexican & Central American History",
    "973": "United States History",
    "974": "Northeastern US History",
    "975": "Southeastern US History",
    "976": "South Central US History",
    "977": "North Central US History",
    "978": "Western US History",
    "979": "Great Basin & Pacific Coast US History",
    "980": "South American History",
    "990": "History of Other Areas",
    "994": "Australian History",
}
